[package]
authors = ["Wim Looman <wim@nemo157.com>"]
name = "multistream"
version = "0.1.0"

[dependencies]
bytes = "0.4.4"
futures = "*"
tokio-io = "0.1.2"

[dependencies.msgio]
path = "../msgio-rs"
